apiVersion: batch/v1
kind: Job
metadata:
  name: gcemeta-example
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: gcemeta-example
        image: mechiru/gcemeta-example:v0.2.1
        env:
        - name: RUST_LOG
          value: debug
