apiVersion: batch/v1
kind: Job
metadata:
  name: gcemeta-example
spec:
  template:
    spec:
      containers:
      - name: gcemeta-example
        image: mechiru/gcemeta-example:v0.1.1
      restartPolicy: OnFailure
